kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: nginx
  name: nginx-deployment
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metatdata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
