kind: Service
apiVersion: v1
metadata:
  labels:
    app: nginx
  name: nginx-service
  namespace: argocd
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
